import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1768776807973 implements MigrationInterface {
    name = 'Initial1768776807973'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`patient_requirements\` (\`id\` varchar(36) NOT NULL, \`patient_id\` varchar(255) NOT NULL, \`type\` enum ('screening', 'medical_report') NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` varchar(500) NULL, \`status\` enum ('pending', 'under_review', 'approved', 'declined') NOT NULL DEFAULT 'pending', \`submitted_at\` datetime NULL, \`approved_by\` varchar(255) NULL, \`approved_at\` datetime NULL, \`declined_by\` varchar(255) NULL, \`declined_at\` datetime NULL, \`created_by\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`patient_supports\` (\`id\` varchar(36) NOT NULL, \`patient_id\` varchar(255) NOT NULL, \`name\` varchar(64) NOT NULL, \`phone\` varchar(11) NOT NULL, \`kinship\` varchar(50) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`referrals\` (\`id\` varchar(36) NOT NULL, \`patient_id\` varchar(255) NOT NULL, \`date\` datetime NOT NULL, \`status\` enum ('scheduled', 'canceled', 'completed', 'no_show') NOT NULL DEFAULT 'scheduled', \`category\` enum ('medical_care', 'legal', 'nursing', 'psychology', 'nutrition', 'physical_training', 'social_work', 'psychiatry', 'neurology', 'ophthalmology') NOT NULL, \`condition\` enum ('in_crisis', 'stable') NOT NULL, \`annotation\` varchar(2000) NULL, \`professional_name\` varchar(64) NULL, \`created_by\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`patients\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(64) NOT NULL, \`email\` varchar(64) NOT NULL, \`password\` varchar(255) NULL, \`avatar_url\` varchar(255) NULL, \`status\` enum ('active', 'inactive', 'pending') NOT NULL DEFAULT 'pending', \`gender\` enum ('male_cis', 'female_cis', 'male_trans', 'female_trans', 'non_binary', 'prefer_not_to_say') NOT NULL DEFAULT 'prefer_not_to_say', \`date_of_birth\` datetime NULL, \`phone\` varchar(11) NULL, \`cpf\` varchar(11) NULL, \`state\` enum ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NULL, \`city\` varchar(255) NULL, \`has_disability\` tinyint(1) NOT NULL DEFAULT '0', \`disability_desc\` varchar(500) NULL, \`need_legal_assistance\` tinyint(1) NOT NULL DEFAULT '0', \`take_medication\` tinyint(1) NOT NULL DEFAULT '0', \`medication_desc\` varchar(500) NULL, \`nmo_diagnosis\` enum ('anti_aqp4_positive', 'anti_mog_positive', 'both_negative', 'no_diagnosis') NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_64e2031265399f5690b0beba6a\` (\`email\`), UNIQUE INDEX \`IDX_5947301223f5a908fd5e372b0f\` (\`cpf\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`appointments\` (\`id\` varchar(36) NOT NULL, \`patient_id\` varchar(255) NOT NULL, \`date\` datetime NOT NULL, \`status\` enum ('scheduled', 'canceled', 'completed', 'no_show') NOT NULL DEFAULT 'scheduled', \`category\` enum ('medical_care', 'legal', 'nursing', 'psychology', 'nutrition', 'physical_training', 'social_work', 'psychiatry', 'neurology', 'ophthalmology') NOT NULL, \`condition\` enum ('in_crisis', 'stable') NOT NULL, \`annotation\` varchar(500) NULL, \`professional_name\` varchar(64) NULL, \`created_by\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tokens\` (\`id\` int NOT NULL AUTO_INCREMENT, \`entity_id\` varchar(255) NULL, \`email\` varchar(255) NULL, \`token\` varchar(255) NOT NULL, \`type\` enum ('access_token', 'refresh_token', 'password_reset', 'invite_user') NOT NULL, \`expires_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(64) NOT NULL, \`email\` varchar(64) NOT NULL, \`password\` varchar(255) NOT NULL, \`avatar_url\` varchar(255) NULL, \`role\` enum ('admin', 'manager', 'nurse', 'specialist') NOT NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`patient_requirements\` ADD CONSTRAINT \`FK_77b87c61cff4793ae6a4ac50070\` FOREIGN KEY (\`patient_id\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patient_supports\` ADD CONSTRAINT \`FK_62c23ddd34837a0c09faf875425\` FOREIGN KEY (\`patient_id\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referrals\` ADD CONSTRAINT \`FK_bb61873c1c10fe8662f540f0625\` FOREIGN KEY (\`patient_id\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD CONSTRAINT \`FK_3330f054416745deaa2cc130700\` FOREIGN KEY (\`patient_id\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP FOREIGN KEY \`FK_3330f054416745deaa2cc130700\``);
        await queryRunner.query(`ALTER TABLE \`referrals\` DROP FOREIGN KEY \`FK_bb61873c1c10fe8662f540f0625\``);
        await queryRunner.query(`ALTER TABLE \`patient_supports\` DROP FOREIGN KEY \`FK_62c23ddd34837a0c09faf875425\``);
        await queryRunner.query(`ALTER TABLE \`patient_requirements\` DROP FOREIGN KEY \`FK_77b87c61cff4793ae6a4ac50070\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`tokens\``);
        await queryRunner.query(`DROP TABLE \`appointments\``);
        await queryRunner.query(`DROP INDEX \`IDX_5947301223f5a908fd5e372b0f\` ON \`patients\``);
        await queryRunner.query(`DROP INDEX \`IDX_64e2031265399f5690b0beba6a\` ON \`patients\``);
        await queryRunner.query(`DROP TABLE \`patients\``);
        await queryRunner.query(`DROP TABLE \`referrals\``);
        await queryRunner.query(`DROP TABLE \`patient_supports\``);
        await queryRunner.query(`DROP TABLE \`patient_requirements\``);
    }

}
