import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1784249906194 implements MigrationInterface {
    name = 'Initial1784249906194'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "survey_submissions_status_enum" AS ENUM('pending_document', 'pending_review', 'declined', 'approved', 'completed')`);
        await queryRunner.query(`CREATE TABLE "survey_submissions" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "status" "survey_submissions_status_enum" NOT NULL DEFAULT 'pending_document', "reason" character varying(500), "survey_token" character varying(36), "updated_by" uuid, "patientId" uuid, CONSTRAINT "REL_10165b4e4752223e175ec71fa5" UNIQUE ("patientId"), CONSTRAINT "PK_8c44889594bc576b9a407e8361a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9d904bf2b6f4eab195f3f98973" ON "survey_submissions" ("survey_token") `);
        await queryRunner.query(`CREATE TYPE "documents_category_enum" AS ENUM('avatar', 'medical_report')`);
        await queryRunner.query(`CREATE TYPE "documents_status_enum" AS ENUM('pending', 'confirmed')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(128) NOT NULL, "filename" character varying(256) NOT NULL, "key" character varying(512) NOT NULL, "url" character varying(2048) NOT NULL, "size" integer NOT NULL, "mime_type" character varying(64) NOT NULL, "category" "documents_category_enum" NOT NULL, "status" "documents_status_enum" NOT NULL DEFAULT 'pending', "userId" uuid NOT NULL, "surveySubmissionId" uuid, CONSTRAINT "REL_5641ae33ce365f605076316249" UNIQUE ("surveySubmissionId"), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e300b5c2e3fefa9d6f8a3f2597" ON "documents" ("userId") `);
        await queryRunner.query(`CREATE TYPE "surveys_status_enum" AS ENUM('pending_signature', 'completed')`);
        await queryRunner.query(`CREATE TYPE "surveys_gender_enum" AS ENUM('male_cis', 'female_cis', 'male_trans', 'female_trans', 'non_binary', 'prefer_not_to_say', 'other')`);
        await queryRunner.query(`CREATE TYPE "surveys_race_enum" AS ENUM('yellow', 'white', 'indigenous', 'mixed_race', 'black', 'prefer_not_to_say')`);
        await queryRunner.query(`CREATE TYPE "surveys_marital_status_enum" AS ENUM('single', 'stable_union', 'married', 'divorced', 'widowed')`);
        await queryRunner.query(`CREATE TYPE "surveys_address_state_enum" AS ENUM('AC', 'AP', 'AL', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')`);
        await queryRunner.query(`CREATE TYPE "surveys_children_school_support_situation_enum" AS ENUM('no_school_age_children', 'lives_with_parent', 'receives_alimony', 'has_children_no_alimony', 'other')`);
        await queryRunner.query(`CREATE TYPE "surveys_family_income_enum" AS ENUM('less_than_one', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten_or_more')`);
        await queryRunner.query(`CREATE TYPE "surveys_housing_situation_enum" AS ENUM('rented', 'borrowed', 'owned', 'family_or_third_party')`);
        await queryRunner.query(`CREATE TYPE "surveys_home_access_level_enum" AS ENUM('full', 'assisted', 'none')`);
        await queryRunner.query(`CREATE TYPE "surveys_education_level_enum" AS ENUM('no_literacy', 'elementary_incomplete', 'elementary_complete', 'high_school_incomplete', 'high_school_complete', 'technical', 'higher_education_incomplete', 'higher_education_complete', 'postgraduate', 'masters', 'doctorate')`);
        await queryRunner.query(`CREATE TYPE "surveys_employment_status_enum" AS ENUM('on_leave_sickness', 'retired', 'retired_disability', 'bpc_loas', 'unemployed', 'student', 'employed_formal', 'self_employed')`);
        await queryRunner.query(`CREATE TYPE "surveys_study_interruption_enum" AS ENUM('did_not_interrupt', 'interrupted_returned', 'interrupted_not_returned')`);
        await queryRunner.query(`CREATE TYPE "surveys_salary_range_enum" AS ENUM('none', 'less_than_one', 'one', 'between_one_and_two', 'between_two_and_three', 'between_four_and_five', 'more_than_six')`);
        await queryRunner.query(`CREATE TYPE "surveys_receives_sickness_benefit_enum" AS ENUM('receiving', 'not_receiving', 'unaware_of_right', 'denied', 'received_no_longer_needed', 'received_converted_to_retirement', 'not_entitled', 'received_suspended')`);
        await queryRunner.query(`CREATE TYPE "surveys_receives_bpc_loas_enum" AS ENUM('receiving', 'never_requested', 'denied', 'not_applicable')`);
        await queryRunner.query(`CREATE TYPE "surveys_diagnosis_enum" AS ENUM('anti_aqp4_positive', 'anti_aqp4_negative', 'anti_mog_positive', 'both_negative')`);
        await queryRunner.query(`CREATE TYPE "surveys_diagnosis_hospital_state_enum" AS ENUM('AC', 'AP', 'AL', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')`);
        await queryRunner.query(`CREATE TYPE "surveys_time_to_diagnosis_unit_enum" AS ENUM('days', 'weeks', 'years')`);
        await queryRunner.query(`CREATE TYPE "surveys_treatment_in_home_city_enum" AS ENUM('lives_in_capital', 'lives_in_interior', 'goes_to_capital', 'goes_to_other_interior')`);
        await queryRunner.query(`CREATE TYPE "surveys_crisis_action_enum" AS ENUM('reference_doctor', 'reference_hospital', 'upa', 'psf', 'hospital_emergency', 'hospital_emergency_other_city', 'no_assistance')`);
        await queryRunner.query(`CREATE TYPE "surveys_follow_up_how_enum" AS ENUM('sus', 'private', 'health_insurance', 'sus_and_insurance', 'sus_and_private', 'not_treating')`);
        await queryRunner.query(`CREATE TYPE "surveys_legal_action_for_medication_enum" AS ENUM('yes_obtained', 'yes_denied', 'no_sus', 'no_insurance', 'buys_medication')`);
        await queryRunner.query(`CREATE TYPE "surveys_visual_impairment_assistance_enum" AS ENUM('all_activities', 'some_activities', 'no')`);
        await queryRunner.query(`CREATE TYPE "surveys_motor_impairment_assistance_enum" AS ENUM('all_activities', 'some_activities', 'no')`);
        await queryRunner.query(`CREATE TYPE "surveys_walking_distance_enum" AS ENUM('less_than_10m', 'between_10_and_500m', 'more_than_500m')`);
        await queryRunner.query(`CREATE TYPE "surveys_bladder_control_enum" AS ENUM('yes', 'yes_urgent', 'no_leak', 'no_catheter', 'no_device', 'no_diapers')`);
        await queryRunner.query(`CREATE TYPE "surveys_bowel_function_enum" AS ENUM('daily', 'every_2_3_days', 'more_than_5_days', 'stool_leakage')`);
        await queryRunner.query(`CREATE TYPE "surveys_blood_type_enum" AS ENUM('A_positive', 'A_negative', 'B_positive', 'B_negative', 'AB_positive', 'AB_negative', 'O_positive', 'O_negative')`);
        await queryRunner.query(`CREATE TYPE "surveys_family_support_enum" AS ENUM('not_need', 'always', 'sometimes', 'not_as_id_like', 'no_family', 'no')`);
        await queryRunner.query(`CREATE TYPE "surveys_fatigue_enum" AS ENUM('always', 'in_heat', 'sometimes', 'no')`);
        await queryRunner.query(`CREATE TYPE "surveys_physical_activity_enum" AS ENUM('four_or_more_week', 'three_week', 'two_week', 'one_week', 'only_physiotherapy', 'no')`);
        await queryRunner.query(`CREATE TYPE "surveys_physical_activity_type_enum" AS ENUM('walking', 'running', 'weight_training', 'pilates', 'yoga', 'swimming', 'water_aerobics', 'cycling', 'dancing', 'soccer', 'martial_arts', 'functional', 'other')`);
        await queryRunner.query(`CREATE TYPE "surveys_exercises_before_nmo_enum" AS ENUM('walking_1_or_2', 'walking_3_or_more', 'running_1_or_2', 'running_3_or_more', 'weight_training', 'swimming_hydro', 'pilates_yoga', 'dancing', 'sports', 'other')`);
        await queryRunner.query(`CREATE TABLE "surveys" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "signature_id" character varying(64), "status" "surveys_status_enum" NOT NULL DEFAULT 'pending_signature', "date_of_birth" date NOT NULL, "gender" "surveys_gender_enum" NOT NULL, "race" "surveys_race_enum", "marital_status" "surveys_marital_status_enum" NOT NULL, "address_cep" character varying(8) NOT NULL, "address_state" "surveys_address_state_enum" NOT NULL, "address_city" character varying(64) NOT NULL, "address_street" character varying(255) NOT NULL, "address_number" character varying(20), "address_neighborhood" character varying(64), "has_lived_elsewhere" boolean NOT NULL, "lived_elsewhere_description" character varying(500), "number_of_children" integer NOT NULL DEFAULT '0', "children_ages" integer array, "children_school_support_situation" "surveys_children_school_support_situation_enum", "family_income" "surveys_family_income_enum" NOT NULL, "housing_situation" "surveys_housing_situation_enum" NOT NULL, "household_size" integer NOT NULL DEFAULT '1', "house_rooms" integer NOT NULL DEFAULT '0', "house_bathrooms" integer NOT NULL DEFAULT '0', "home_access_level" "surveys_home_access_level_enum" NOT NULL, "transport_modes" text array NOT NULL DEFAULT '{}', "education_level" "surveys_education_level_enum" NOT NULL, "employment_status" "surveys_employment_status_enum" NOT NULL, "study_interruption" "surveys_study_interruption_enum", "profession" character varying(64), "job_title" character varying(64), "salary_range" "surveys_salary_range_enum" NOT NULL, "dismissed_after_diagnosis" boolean, "changed_profession" boolean, "changed_profession_to" character varying(64), "current_job_is_pcd" boolean, "receives_sickness_benefit" "surveys_receives_sickness_benefit_enum" NOT NULL, "receives_bpc_loas" "surveys_receives_bpc_loas_enum" NOT NULL, "diagnosis" "surveys_diagnosis_enum" NOT NULL, "first_crisis_symptoms" text array NOT NULL DEFAULT '{}', "affected_areas" text array NOT NULL DEFAULT '{}', "diagnosing_doctor_name" character varying(128), "diagnosis_hospital_name" character varying(128), "diagnosis_hospital_cep" character varying(8), "diagnosis_hospital_state" "surveys_diagnosis_hospital_state_enum", "diagnosis_hospital_city" character varying(64), "diagnosis_hospital_street" character varying(255), "diagnosis_date" date NOT NULL, "diagnosis_document" character varying(255), "current_neurologist" character varying(128), "current_treatment_hospital" character varying(128), "current_treatment_hospital_cep" character varying(8), "specialists_before_diagnosis" text array NOT NULL DEFAULT '{}', "time_to_diagnosis" integer NOT NULL, "time_to_diagnosis_unit" "surveys_time_to_diagnosis_unit_enum" NOT NULL, "suspected_multiple_sclerosis" boolean, "other_suspected_diseases" character varying(200), "crises_before_diagnosis" integer, "crises_since_diagnosis" integer, "treatment_in_home_city" "surveys_treatment_in_home_city_enum" NOT NULL, "has_neurologists_in_city" boolean, "crisis_action" "surveys_crisis_action_enum" NOT NULL, "follow_up_specialties" text array NOT NULL DEFAULT '{}', "other_follow_up_professionals" text array NOT NULL DEFAULT '{}', "follow_up_how" "surveys_follow_up_how_enum" NOT NULL, "has_health_insurance" boolean NOT NULL, "nmo_medications" text array NOT NULL DEFAULT '{}', "crises_after_medication" integer, "legal_action_for_medication" "surveys_legal_action_for_medication_enum" NOT NULL, "general_medications" text array NOT NULL DEFAULT '{}', "has_visual_alteration" boolean NOT NULL, "uses_visual_cane" boolean, "visual_impairment_assistance" "surveys_visual_impairment_assistance_enum", "visual_assistive_technologies" text array NOT NULL DEFAULT '{}', "uses_wheelchair" boolean NOT NULL, "has_motor_sequelae" boolean NOT NULL, "motor_impairment_assistance" "surveys_motor_impairment_assistance_enum", "walking_distance" "surveys_walking_distance_enum", "uses_walking_aid" boolean NOT NULL, "bladder_control" "surveys_bladder_control_enum" NOT NULL, "bowel_function" "surveys_bowel_function_enum" NOT NULL, "other_sequelae" character varying(300), "psychological_meds_before_nmo" boolean NOT NULL, "psychological_meds_after_nmo" boolean NOT NULL, "psychological_diagnosis_after_nmo" boolean NOT NULL, "blood_type" "surveys_blood_type_enum", "has_other_disease" boolean NOT NULL, "other_disease_description" character varying(200), "family_support" "surveys_family_support_enum" NOT NULL, "fatigue" "surveys_fatigue_enum" NOT NULL, "physical_activity" "surveys_physical_activity_enum" NOT NULL, "physical_activity_type" "surveys_physical_activity_type_enum", "exercised_before_nmo" boolean NOT NULL, "exercises_before_nmo" "surveys_exercises_before_nmo_enum", "information_sources" text array NOT NULL DEFAULT '{}', "life_perception" character varying(800) NOT NULL, "dreams" character varying(800) NOT NULL, "additional_info" character varying(800) NOT NULL, "patientId" uuid NOT NULL, CONSTRAINT "REL_777cd9a37556696f4e2218179c" UNIQUE ("patientId"), CONSTRAINT "PK_1b5e3d4aaeb2321ffa98498c971" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "users_role_enum" AS ENUM('admin', 'member', 'specialist', 'patient')`);
        await queryRunner.query(`CREATE TYPE "users_status_enum" AS ENUM('active', 'inactive', 'pending')`);
        await queryRunner.query(`CREATE TYPE "users_specialty_enum" AS ENUM('medical_care', 'legal', 'nursing', 'psychology', 'nutrition', 'physical_training', 'social_work', 'psychiatry', 'neurology', 'ophthalmology')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(64) NOT NULL, "email" character varying(254) NOT NULL, "password" character varying(64) NOT NULL, "avatar_url" character varying(2048), "phone" character varying(11), "role" "users_role_enum" NOT NULL, "features" text array NOT NULL DEFAULT '{}', "status" "users_status_enum" NOT NULL DEFAULT 'active', "specialty" "users_specialty_enum", "registration_id" character varying(32), "cpf" character varying(11), "sus_id" character varying(15), "support_contacts" jsonb, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_345c3e629924f513952b2e9bf4b" UNIQUE ("registration_id"), CONSTRAINT "UQ_230b925048540454c8b4c481e1c" UNIQUE ("cpf"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_51b8b26ac168fbe7d6f5653e6c" ON "users" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "appointments_status_enum" AS ENUM('scheduled', 'canceled', 'completed', 'no_show')`);
        await queryRunner.query(`CREATE TYPE "appointments_category_enum" AS ENUM('medical_care', 'legal', 'nursing', 'psychology', 'nutrition', 'physical_training', 'social_work', 'psychiatry', 'neurology', 'ophthalmology')`);
        await queryRunner.query(`CREATE TYPE "appointments_condition_enum" AS ENUM('in_crisis', 'stable')`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "date" TIMESTAMP NOT NULL, "status" "appointments_status_enum" NOT NULL DEFAULT 'scheduled', "category" "appointments_category_enum" NOT NULL, "condition" "appointments_condition_enum" NOT NULL, "annotation" character varying(500), "professional_name" character varying(64), "created_by" uuid NOT NULL, "patientId" uuid NOT NULL, "specialistId" uuid, CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_13c2e57cb81b44f062ba24df57" ON "appointments" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3d4f3685b710e33ed39d38592" ON "appointments" ("specialistId") `);
        await queryRunner.query(`CREATE TYPE "patient_requirements_type_enum" AS ENUM('screening', 'medical_report')`);
        await queryRunner.query(`CREATE TYPE "patient_requirements_status_enum" AS ENUM('pending', 'under_review', 'approved', 'declined')`);
        await queryRunner.query(`CREATE TABLE "patient_requirements" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying(255) NOT NULL, "description" character varying(500), "type" "patient_requirements_type_enum" NOT NULL, "status" "patient_requirements_status_enum" NOT NULL DEFAULT 'pending', "submitted_at" TIMESTAMP, "updated_by" uuid, "created_by" uuid NOT NULL, "patientId" uuid NOT NULL, CONSTRAINT "PK_7b5a168693269e452011bff093f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cbbcca403201b580e96ae7cdd6" ON "patient_requirements" ("patientId") `);
        await queryRunner.query(`CREATE TYPE "referrals_status_enum" AS ENUM('scheduled', 'canceled', 'completed', 'no_show')`);
        await queryRunner.query(`CREATE TYPE "referrals_category_enum" AS ENUM('medical_care', 'legal', 'nursing', 'psychology', 'nutrition', 'physical_training', 'social_work', 'psychiatry', 'neurology', 'ophthalmology')`);
        await queryRunner.query(`CREATE TYPE "referrals_condition_enum" AS ENUM('in_crisis', 'stable')`);
        await queryRunner.query(`CREATE TABLE "referrals" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "date" TIMESTAMP NOT NULL, "status" "referrals_status_enum" NOT NULL DEFAULT 'scheduled', "category" "referrals_category_enum" NOT NULL, "condition" "referrals_condition_enum" NOT NULL, "annotation" character varying(500), "professional_name" character varying(64), "created_by" uuid NOT NULL, "patientId" uuid NOT NULL, "specialistId" uuid, CONSTRAINT "PK_ea9980e34f738b6252817326c08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1a3687f43c0a90d68524034085" ON "referrals" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9736c59593d20679f2368d27b7" ON "referrals" ("specialistId") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "token_hash" character varying(64) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "UQ_abaa9e068cdd390bc5210f79884" UNIQUE ("token_hash"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_57de40bc620f456c7311aa3a1e" ON "sessions" ("userId") `);
        await queryRunner.query(`CREATE TYPE "tokens_type_enum" AS ENUM('password_reset', 'invite_user')`);
        await queryRunner.query(`CREATE TABLE "tokens" ("id" uuid NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "email" character varying(64), "token" character varying(254) NOT NULL, "type" "tokens_type_enum" NOT NULL, "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "UQ_6a8ca5961656d13c16c04079dd3" UNIQUE ("token"), CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8769073e38c365f315426554ca" ON "tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a8ca5961656d13c16c04079dd" ON "tokens" ("token") `);
        await queryRunner.query(`ALTER TABLE "survey_submissions" ADD CONSTRAINT "FK_10165b4e4752223e175ec71fa5a" FOREIGN KEY ("patientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_e300b5c2e3fefa9d6f8a3f25975" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_5641ae33ce365f6050763162492" FOREIGN KEY ("surveySubmissionId") REFERENCES "survey_submissions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surveys" ADD CONSTRAINT "FK_777cd9a37556696f4e2218179cb" FOREIGN KEY ("patientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d" FOREIGN KEY ("patientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_b3d4f3685b710e33ed39d38592a" FOREIGN KEY ("specialistId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_requirements" ADD CONSTRAINT "FK_cbbcca403201b580e96ae7cdd62" FOREIGN KEY ("patientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_1a3687f43c0a90d685240340852" FOREIGN KEY ("patientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_9736c59593d20679f2368d27b77" FOREIGN KEY ("specialistId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_9736c59593d20679f2368d27b77"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_1a3687f43c0a90d685240340852"`);
        await queryRunner.query(`ALTER TABLE "patient_requirements" DROP CONSTRAINT "FK_cbbcca403201b580e96ae7cdd62"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_b3d4f3685b710e33ed39d38592a"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d"`);
        await queryRunner.query(`ALTER TABLE "surveys" DROP CONSTRAINT "FK_777cd9a37556696f4e2218179cb"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_5641ae33ce365f6050763162492"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_e300b5c2e3fefa9d6f8a3f25975"`);
        await queryRunner.query(`ALTER TABLE "survey_submissions" DROP CONSTRAINT "FK_10165b4e4752223e175ec71fa5a"`);
        await queryRunner.query(`DROP INDEX "IDX_6a8ca5961656d13c16c04079dd"`);
        await queryRunner.query(`DROP INDEX "IDX_8769073e38c365f315426554ca"`);
        await queryRunner.query(`DROP TABLE "tokens"`);
        await queryRunner.query(`DROP TYPE "tokens_type_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_57de40bc620f456c7311aa3a1e"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "IDX_9736c59593d20679f2368d27b7"`);
        await queryRunner.query(`DROP INDEX "IDX_1a3687f43c0a90d68524034085"`);
        await queryRunner.query(`DROP TABLE "referrals"`);
        await queryRunner.query(`DROP TYPE "referrals_condition_enum"`);
        await queryRunner.query(`DROP TYPE "referrals_category_enum"`);
        await queryRunner.query(`DROP TYPE "referrals_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_cbbcca403201b580e96ae7cdd6"`);
        await queryRunner.query(`DROP TABLE "patient_requirements"`);
        await queryRunner.query(`DROP TYPE "patient_requirements_status_enum"`);
        await queryRunner.query(`DROP TYPE "patient_requirements_type_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_b3d4f3685b710e33ed39d38592"`);
        await queryRunner.query(`DROP INDEX "IDX_13c2e57cb81b44f062ba24df57"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TYPE "appointments_condition_enum"`);
        await queryRunner.query(`DROP TYPE "appointments_category_enum"`);
        await queryRunner.query(`DROP TYPE "appointments_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "IDX_51b8b26ac168fbe7d6f5653e6c"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "users_specialty_enum"`);
        await queryRunner.query(`DROP TYPE "users_status_enum"`);
        await queryRunner.query(`DROP TYPE "users_role_enum"`);
        await queryRunner.query(`DROP TABLE "surveys"`);
        await queryRunner.query(`DROP TYPE "surveys_exercises_before_nmo_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_physical_activity_type_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_physical_activity_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_fatigue_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_family_support_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_blood_type_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_bowel_function_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_bladder_control_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_walking_distance_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_motor_impairment_assistance_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_visual_impairment_assistance_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_legal_action_for_medication_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_follow_up_how_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_crisis_action_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_treatment_in_home_city_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_time_to_diagnosis_unit_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_diagnosis_hospital_state_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_diagnosis_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_receives_bpc_loas_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_receives_sickness_benefit_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_salary_range_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_study_interruption_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_employment_status_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_education_level_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_home_access_level_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_housing_situation_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_family_income_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_children_school_support_situation_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_address_state_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_marital_status_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_race_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_gender_enum"`);
        await queryRunner.query(`DROP TYPE "surveys_status_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_e300b5c2e3fefa9d6f8a3f2597"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "documents_status_enum"`);
        await queryRunner.query(`DROP TYPE "documents_category_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_9d904bf2b6f4eab195f3f98973"`);
        await queryRunner.query(`DROP TABLE "survey_submissions"`);
        await queryRunner.query(`DROP TYPE "survey_submissions_status_enum"`);
    }

}
