name: abnmo_test

services:
  abnmo_db:
    image: postgres:17-alpine
    container_name: 'postgres-test'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - abnmo_pg_test_data:/var/lib/postgresql/data

volumes:
  abnmo_pg_test_data:
