name: svm_dev

services:
  database:
    image: mysql:8.4
    container_name: 'svm_dev_mysql'
    env_file:
      - ../../../.env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - svm_dev_mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10
    networks:
      - svm_dev_network

  api:
    build:
      context: ../../..
      dockerfile: infra/docker/dev/Dockerfile
    image: svm-dev-api
    container_name: 'svm_dev_api'
    ports:
      - '${API_PORT}:3333'
    env_file:
      - ../../../.env.docker
    depends_on:
      database:
        condition: service_healthy
    networks:
      - svm_dev_network

networks:
  svm_dev_network:
    driver: bridge

volumes:
  svm_dev_mysql_data:
