import { z } from 'zod';

import { BRAZIL_STATES } from '@/domain/enums/shared';
import {
  AFFECTED_AREAS,
  BLADDER_CONTROLS,
  BLOOD_TYPES,
  BOWEL_FUNCTIONS,
  BPC_LOAS_STATUSES,
  CHILDREN_SCHOOL_SUPPORT_SITUATIONS,
  CRISIS_ACTIONS,
  DAILY_ACTIVITY_ASSISTANCES,
  DIAGNOSIS_TYPES,
  EDUCATION_LEVELS,
  EMPLOYMENT_STATUSES,
  EXERCISES_BEFORE_NMO,
  FAMILY_INCOMES,
  FAMILY_SUPPORTS,
  FATIGUE_LEVELS,
  FIRST_CRISIS_SYMPTOMS,
  FOLLOW_UP_HOW,
  FOLLOW_UP_SPECIALTIES,
  GENDERS,
  HOME_ACCESS_LEVELS,
  HOUSING_SITUATIONS,
  INFORMATION_SOURCES,
  LEGAL_ACTIONS,
  MARITAL_STATUSES,
  PHYSICAL_ACTIVITY_FREQUENCIES,
  PHYSICAL_ACTIVITY_TYPES,
  RACES,
  SALARY_RANGES,
  SICKNESS_BENEFIT_STATUSES,
  SPECIALTIES_BEFORE_DIAGNOSIS,
  STUDY_INTERRUPTION_SITUATIONS,
  SURVEY_STATUSES,
  TIME_UNITS,
  TRANSPORT_MODES,
  TREATMENT_LOCATIONS,
  VISUAL_ASSISTIVE_TECHNOLOGIES,
  WALKING_DISTANCES,
} from '@/domain/enums/surveys';

import { baseEntitySchema } from '../base';
import { cepSchema } from '../shared';

export const surveySchema = baseEntitySchema.extend({
  // Base
  signatureId: z.string().max(64).nullable(),
  status: z.enum(SURVEY_STATUSES).default('pending_signature'),
  // About
  dateOfBirth: z.string().date(),
  gender: z.enum(GENDERS),
  race: z.enum(RACES).nullable(),
  maritalStatus: z.enum(MARITAL_STATUSES),
  addressCep: cepSchema,
  addressState: z.enum(BRAZIL_STATES),
  addressCity: z.string().min(1),
  addressStreet: z.string().min(1),
  addressNumber: z.string().nullable(),
  addressNeighborhood: z.string().min(1).nullable(),
  hasLivedElsewhere: z.boolean(),
  livedElsewhereDescription: z.string().max(500).nullable(),
  // Family
  numberOfChildren: z.number().min(0),
  childrenAges: z.array(z.number()).nullable(),
  childrenSchoolSupportSituation: z
    .enum(CHILDREN_SCHOOL_SUPPORT_SITUATIONS)
    .nullable(),
  familyIncome: z.enum(FAMILY_INCOMES),
  housingSituation: z.enum(HOUSING_SITUATIONS),
  householdSize: z.number().min(1),
  houseRooms: z.number().min(0),
  houseBathrooms: z.number().min(0),
  homeAccessLevel: z.enum(HOME_ACCESS_LEVELS),
  transportModes: z.array(z.enum(TRANSPORT_MODES)).min(1),
  // Journey
  educationLevel: z.enum(EDUCATION_LEVELS),
  employmentStatus: z.enum(EMPLOYMENT_STATUSES),
  studyInterruption: z.enum(STUDY_INTERRUPTION_SITUATIONS).nullable(),
  profession: z.string().nullable(),
  jobTitle: z.string().nullable(),
  salaryRange: z.enum(SALARY_RANGES),
  dismissedAfterDiagnosis: z.boolean().nullable(),
  changedProfession: z.boolean().nullable(),
  changedProfessionTo: z.string().nullable(),
  currentJobIsPcd: z.boolean().nullable(),
  receivesSicknessBenefit: z.enum(SICKNESS_BENEFIT_STATUSES),
  receivesBpcLoas: z.enum(BPC_LOAS_STATUSES),
  // Diagnosis
  diagnosis: z.enum(DIAGNOSIS_TYPES),
  firstCrisisSymptoms: z.array(z.enum(FIRST_CRISIS_SYMPTOMS)).min(1),
  affectedAreas: z.array(z.enum(AFFECTED_AREAS)).min(1),
  diagnosingDoctorName: z.string().nullable(),
  diagnosisHospitalName: z.string().nullable(),
  diagnosisHospitalCep: cepSchema.nullable(),
  diagnosisHospitalState: z.enum(BRAZIL_STATES).nullable(),
  diagnosisHospitalCity: z.string().nullable(),
  diagnosisHospitalStreet: z.string().nullable(),
  diagnosisDate: z.coerce.date(),
  diagnosisDocument: z.string().nullable(),
  currentNeurologist: z.string().nullable(),
  currentTreatmentHospital: z.string().nullable(),
  currentTreatmentHospitalCep: cepSchema.nullable(),
  specialistsBeforeDiagnosis: z
    .array(z.enum(SPECIALTIES_BEFORE_DIAGNOSIS))
    .min(1),
  timeToDiagnosis: z.number().min(0),
  timeToDiagnosisUnit: z.enum(TIME_UNITS),
  suspectedMultipleSclerosis: z.boolean().nullable(),
  otherSuspectedDiseases: z.string().nullable(),
  crisesBeforeDiagnosis: z.number().min(0).nullable(),
  crisesSinceDiagnosis: z.number().min(0).nullable(),
  treatmentInHomeCity: z.enum(TREATMENT_LOCATIONS),
  hasNeurologistsInCity: z.boolean().nullable(),
  crisisAction: z.enum(CRISIS_ACTIONS),
  // Follow-up
  followUpSpecialties: z.array(z.enum(FOLLOW_UP_SPECIALTIES)).min(1),
  otherFollowUpProfessionals: z.array(z.string()).default([]),
  followUpHow: z.enum(FOLLOW_UP_HOW),
  hasHealthInsurance: z.boolean(),
  nmoMedications: z.array(z.string()).default([]),
  crisesAfterMedication: z.number().min(0).nullable(),
  legalActionForMedication: z.enum(LEGAL_ACTIONS),
  generalMedications: z.array(z.string()).default([]),
  hasVisualAlteration: z.boolean(),
  usesVisualCane: z.boolean().nullable(),
  visualImpairmentAssistance: z.enum(DAILY_ACTIVITY_ASSISTANCES).nullable(),
  visualAssistiveTechnologies: z
    .array(z.enum(VISUAL_ASSISTIVE_TECHNOLOGIES))
    .default([]),
  usesWheelchair: z.boolean(),
  hasMotorSequelae: z.boolean(),
  motorImpairmentAssistance: z.enum(DAILY_ACTIVITY_ASSISTANCES).nullable(),
  walkingDistance: z.enum(WALKING_DISTANCES).nullable(),
  usesWalkingAid: z.boolean(),
  bladderControl: z.enum(BLADDER_CONTROLS),
  bowelFunction: z.enum(BOWEL_FUNCTIONS),
  otherSequelae: z.string().max(300).nullable(),
  psychologicalMedsBeforeNmo: z.boolean(),
  psychologicalMedsAfterNmo: z.boolean(),
  psychologicalDiagnosisAfterNmo: z.boolean(),
  bloodType: z.enum(BLOOD_TYPES).nullable(),
  hasOtherDisease: z.boolean(),
  otherDiseaseDescription: z.string().max(200).nullable(),
  // Daily life
  familySupport: z.enum(FAMILY_SUPPORTS),
  fatigue: z.enum(FATIGUE_LEVELS),
  physicalActivity: z.enum(PHYSICAL_ACTIVITY_FREQUENCIES),
  physicalActivityType: z.enum(PHYSICAL_ACTIVITY_TYPES).nullable(),
  exercisedBeforeNmo: z.boolean(),
  exercisesBeforeNmo: z.enum(EXERCISES_BEFORE_NMO).nullable(),
  informationSources: z.array(z.enum(INFORMATION_SOURCES)).min(1),
  lifePerception: z.string().max(800),
  dreams: z.string().max(800),
  additionalInfo: z.string().max(800),
});
export type SurveySchema = z.infer<typeof surveySchema>;
