import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { can } from '@/common/authorization/can';
import type { RequestUser } from '@/common/types';
import { Survey } from '@/domain/entities/survey';
import type { SurveyDetailsResponse } from '@/domain/schemas/surveys/responses';

interface GetSurveyUseCaseInput {
  user: RequestUser;
  id: string;
}

@Injectable()
export class GetSurveyUseCase {
  constructor(
    @InjectRepository(Survey)
    private readonly surveysRepository: Repository<Survey>,
  ) {}

  async execute({
    user,
    id,
  }: GetSurveyUseCaseInput): Promise<SurveyDetailsResponse> {
    const survey = await this.surveysRepository.findOne({
      relations: { patient: true },
      where: { id },
      select: {
        id: true,
        status: true,
        signatureId: true,
        signatureDocumentId: true,
        dateOfBirth: true,
        gender: true,
        race: true,
        maritalStatus: true,
        addressCep: true,
        addressState: true,
        addressCity: true,
        addressStreet: true,
        addressNumber: true,
        addressNeighborhood: true,
        hasLivedElsewhere: true,
        livedElsewhereDescription: true,
        numberOfChildren: true,
        childrenAges: true,
        childrenSchoolSupportSituation: true,
        familyIncome: true,
        housingSituation: true,
        householdSize: true,
        houseRooms: true,
        houseBathrooms: true,
        homeAccessLevel: true,
        transportModes: true,
        educationLevel: true,
        employmentStatus: true,
        studyInterruption: true,
        profession: true,
        jobTitle: true,
        salaryRange: true,
        dismissedAfterDiagnosis: true,
        changedProfession: true,
        changedProfessionTo: true,
        currentJobIsPcd: true,
        receivesSicknessBenefit: true,
        receivesBpcLoas: true,
        diagnosis: true,
        firstCrisisSymptoms: true,
        affectedAreas: true,
        diagnosingDoctorName: true,
        diagnosisHospitalName: true,
        diagnosisHospitalCep: true,
        diagnosisHospitalState: true,
        diagnosisHospitalCity: true,
        diagnosisHospitalStreet: true,
        diagnosisDate: true,
        diagnosisDocument: true,
        currentNeurologist: true,
        currentTreatmentHospital: true,
        currentTreatmentHospitalCep: true,
        specialistsBeforeDiagnosis: true,
        timeToDiagnosisInDays: true,
        suspectedMultipleSclerosis: true,
        otherSuspectedDiseases: true,
        crisesBeforeDiagnosis: true,
        crisesSinceDiagnosis: true,
        treatmentInHomeCity: true,
        hasNeurologistsInCity: true,
        crisisAction: true,
        followUpSpecialties: true,
        otherFollowUpProfessionals: true,
        followUpHow: true,
        hasHealthInsurance: true,
        nmoMedications: true,
        crisesAfterMedication: true,
        legalActionForMedication: true,
        generalMedications: true,
        hasVisualAlteration: true,
        usesVisualCane: true,
        visualImpairmentAssistance: true,
        visualAssistiveTechnologies: true,
        usesWheelchair: true,
        hasMotorSequelae: true,
        motorImpairmentAssistance: true,
        walkingDistance: true,
        usesWalkingAid: true,
        bladderControl: true,
        bowelFunction: true,
        otherSequelae: true,
        psychologicalMedsBeforeNmo: true,
        psychologicalMedsAfterNmo: true,
        psychologicalDiagnosisAfterNmo: true,
        bloodType: true,
        hasOtherDisease: true,
        otherDiseaseDescription: true,
        familySupport: true,
        fatigue: true,
        physicalActivity: true,
        physicalActivityType: true,
        exercisedBeforeNmo: true,
        exercisesBeforeNmo: true,
        informationSources: true,
        lifePerception: true,
        dreams: true,
        additionalInfo: true,
        updatedAt: true,
        createdAt: true,
        patient: {
          id: true,
          name: true,
          phone: true,
          email: true,
          cpf: true,
          susId: true,
        },
      },
    });

    if (!survey) {
      throw new NotFoundException('Catalogação não encontrada.');
    }

    can(user, ['read:survey', 'read:survey:others'], survey.patient.id);

    return {
      id: survey.id,
      status: survey.status,
      signatureId: survey.signatureId,
      signatureDocumentId: survey.signatureDocumentId,
      dateOfBirth: survey.dateOfBirth,
      gender: survey.gender,
      race: survey.race,
      maritalStatus: survey.maritalStatus,
      addressCep: survey.addressCep,
      addressState: survey.addressState,
      addressCity: survey.addressCity,
      addressStreet: survey.addressStreet,
      addressNumber: survey.addressNumber,
      addressNeighborhood: survey.addressNeighborhood,
      hasLivedElsewhere: survey.hasLivedElsewhere,
      livedElsewhereDescription: survey.livedElsewhereDescription,
      numberOfChildren: survey.numberOfChildren,
      childrenAges: survey.childrenAges,
      childrenSchoolSupportSituation: survey.childrenSchoolSupportSituation,
      familyIncome: survey.familyIncome,
      housingSituation: survey.housingSituation,
      householdSize: survey.householdSize,
      houseRooms: survey.houseRooms,
      houseBathrooms: survey.houseBathrooms,
      homeAccessLevel: survey.homeAccessLevel,
      transportModes: survey.transportModes,
      educationLevel: survey.educationLevel,
      employmentStatus: survey.employmentStatus,
      studyInterruption: survey.studyInterruption,
      profession: survey.profession,
      jobTitle: survey.jobTitle,
      salaryRange: survey.salaryRange,
      dismissedAfterDiagnosis: survey.dismissedAfterDiagnosis,
      changedProfession: survey.changedProfession,
      changedProfessionTo: survey.changedProfessionTo,
      currentJobIsPcd: survey.currentJobIsPcd,
      receivesSicknessBenefit: survey.receivesSicknessBenefit,
      receivesBpcLoas: survey.receivesBpcLoas,
      diagnosis: survey.diagnosis,
      firstCrisisSymptoms: survey.firstCrisisSymptoms,
      affectedAreas: survey.affectedAreas,
      diagnosingDoctorName: survey.diagnosingDoctorName,
      diagnosisHospitalName: survey.diagnosisHospitalName,
      diagnosisHospitalCep: survey.diagnosisHospitalCep,
      diagnosisHospitalState: survey.diagnosisHospitalState,
      diagnosisHospitalCity: survey.diagnosisHospitalCity,
      diagnosisHospitalStreet: survey.diagnosisHospitalStreet,
      diagnosisDate: survey.diagnosisDate,
      diagnosisDocument: survey.diagnosisDocument,
      currentNeurologist: survey.currentNeurologist,
      currentTreatmentHospital: survey.currentTreatmentHospital,
      currentTreatmentHospitalCep: survey.currentTreatmentHospitalCep,
      specialistsBeforeDiagnosis: survey.specialistsBeforeDiagnosis,
      timeToDiagnosisInDays: survey.timeToDiagnosisInDays,
      suspectedMultipleSclerosis: survey.suspectedMultipleSclerosis,
      otherSuspectedDiseases: survey.otherSuspectedDiseases,
      crisesBeforeDiagnosis: survey.crisesBeforeDiagnosis,
      crisesSinceDiagnosis: survey.crisesSinceDiagnosis,
      treatmentInHomeCity: survey.treatmentInHomeCity,
      hasNeurologistsInCity: survey.hasNeurologistsInCity,
      crisisAction: survey.crisisAction,
      followUpSpecialties: survey.followUpSpecialties,
      otherFollowUpProfessionals: survey.otherFollowUpProfessionals,
      followUpHow: survey.followUpHow,
      hasHealthInsurance: survey.hasHealthInsurance,
      nmoMedications: survey.nmoMedications,
      crisesAfterMedication: survey.crisesAfterMedication,
      legalActionForMedication: survey.legalActionForMedication,
      generalMedications: survey.generalMedications,
      hasVisualAlteration: survey.hasVisualAlteration,
      usesVisualCane: survey.usesVisualCane,
      visualImpairmentAssistance: survey.visualImpairmentAssistance,
      visualAssistiveTechnologies: survey.visualAssistiveTechnologies,
      usesWheelchair: survey.usesWheelchair,
      hasMotorSequelae: survey.hasMotorSequelae,
      motorImpairmentAssistance: survey.motorImpairmentAssistance,
      walkingDistance: survey.walkingDistance,
      usesWalkingAid: survey.usesWalkingAid,
      bladderControl: survey.bladderControl,
      bowelFunction: survey.bowelFunction,
      otherSequelae: survey.otherSequelae,
      psychologicalMedsBeforeNmo: survey.psychologicalMedsBeforeNmo,
      psychologicalMedsAfterNmo: survey.psychologicalMedsAfterNmo,
      psychologicalDiagnosisAfterNmo: survey.psychologicalDiagnosisAfterNmo,
      bloodType: survey.bloodType,
      hasOtherDisease: survey.hasOtherDisease,
      otherDiseaseDescription: survey.otherDiseaseDescription,
      familySupport: survey.familySupport,
      fatigue: survey.fatigue,
      physicalActivity: survey.physicalActivity,
      physicalActivityType: survey.physicalActivityType,
      exercisedBeforeNmo: survey.exercisedBeforeNmo,
      exercisesBeforeNmo: survey.exercisesBeforeNmo,
      informationSources: survey.informationSources,
      lifePerception: survey.lifePerception,
      dreams: survey.dreams,
      additionalInfo: survey.additionalInfo,
      updatedAt: survey.updatedAt,
      createdAt: survey.createdAt,
      patient: {
        id: survey.patient.id,
        name: survey.patient.name,
        phone: survey.patient.phone,
        email: survey.patient.email,
        cpf: survey.patient.cpf,
        susId: survey.patient.susId,
      },
    };
  }
}
